EXP_NAME: MAPL
SEED: 42

DATASET:
  datadir: ./datasets/BHAD
  texture_source_dir: ./datasets/dtd/images
  anomaly_mask_info: ./anomaly_mask.json
  target: null
  resize: 
    - 288
    - 288
  imagesize: 256
  structure_grid_size: 8
  transparency_range:
    - 0.15 # under bound
    - 1. # upper bound
  perlin_scale: 6
  min_perlin_scale: 0
  perlin_noise_threshold: 0.5

DATALOADER:
  batch_size: 8
  num_workers: 0

MEMORYBANK:
  nb_memory_sample: 30

PSEUDOLABELER:
  num_PseudoLabeler: 2 #记得改

MODEL:
  feature_extractor_name: resnet18

TRAIN:
  batch_size: 8
  num_training_steps: 500 #记得改
  l1_weight: 0.6
  focal_weight: 0.4
  focal_alpha: null
  focal_gamma: 4
  use_wandb: False
  epochs: 200

OPTIMIZER:
  lr: 0.003
  weight_decay: 0.0005

SCHEDULER:
  min_lr: 0.0001
  warmup_ratio: 0.1
  use_scheduler: True

LOG:
  log_interval: 1
  eval_interval: 100

RESULT:
  savedir: ./saved_model